/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.utp.pizzatime.view;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PERSONAL
 */
public class Pedido_ingredientes extends javax.swing.JPanel {

    /**
     * Creates new form Pedido_ingredientes
     */
    
    JPopupMenu popmenuanticlick; //para q al hacer anticlick en un row se pueda eliminar
    JMenuItem elimitem;
    
    public Pedido_ingredientes() {
        initComponents();
        
        table_head_color(tbped_ing, tbstockactualpeding);
        popmenuanticlick = new JPopupMenu();
        elimitem = new JMenuItem("Eliminar");
        elimitem.addActionListener(e -> elim_row_peding());
        popmenuanticlick.add(elimitem); 
        
        MouseListener popuplistens = new PopupListener();//es un obj PopupListener, solo funciona pq no tiene constructor, solo se ve interfaz generica
        tbped_ing.addMouseListener(popuplistens);  
        
        
        //JTableHeader tableheader= tbped_ing.getTableHeader();
    }
    
    class PopupListener extends MouseAdapter{//clase q reescribe los eventos para q se ejecute el metodo chiquito ese
        @Override
        public void mousePressed(MouseEvent e){
            
            plswork(e);          
        }
        
        @Override
        public void mouseReleased(MouseEvent e){
            
            plswork(e);    
        }
        
        public void plswork(MouseEvent e){
            if (e.isPopupTrigger()) {
                popmenuanticlick.show(e.getComponent(), e.getX(), e.getY());//enseña el menu en donde esta el mouse
                
            }
            
        }
        
    }
    
    private void table_head_color(JTable tbped_ing, JTable tbstockactualpeding){
        DefaultTableCellRenderer header_ren = new DefaultTableCellRenderer();//deja personalizar, pinta celdas en una Jtable

        header_ren.setBackground(new Color(0,109,86));//color del bg
        header_ren.setForeground(Color.LIGHT_GRAY);//color del texto
        header_ren.setHorizontalAlignment(SwingConstants.CENTER);//lo pone en el centro
        
        tbped_ing.getTableHeader().setDefaultRenderer(header_ren);//agarra el header y le pone la cosa personalizada
        tbstockactualpeding.getTableHeader().setDefaultRenderer(header_ren);
}
    
    private void elim_row_peding(){
        DefaultTableModel tb_model_peding = (DefaultTableModel) tbped_ing.getModel();
        int row= tbped_ing.getSelectedRow();
        
        tb_model_peding.removeRow(row);//ya q no guarda hasta q se presiona el boton de pedir
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbonomingre = new javax.swing.JComboBox<>();
        txtcantcajas = new javax.swing.JTextField();
        btnaddingadmin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbped_ing = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txttotalpedido_ing = new javax.swing.JLabel();
        btnpediringadmin = new javax.swing.JButton();
        btncancelingadmin = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbstockactualpeding = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(770, 524));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 109, 86));
        jLabel1.setText("Pedido de Ingredientes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(110, 104, 104));
        jLabel2.setText("Ingrediente :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 104, 104));
        jLabel3.setText("Cantidad Cajas :");

        cbonomingre.setForeground(new java.awt.Color(110, 104, 104));
        cbonomingre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbonomingre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        cbonomingre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbonomingre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbonomingreActionPerformed(evt);
            }
        });

        txtcantcajas.setForeground(new java.awt.Color(110, 104, 104));
        txtcantcajas.setText("jTextField1");
        txtcantcajas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        btnaddingadmin.setBackground(new java.awt.Color(204, 204, 204));
        btnaddingadmin.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnaddingadmin.setForeground(new java.awt.Color(0, 109, 86));
        btnaddingadmin.setText("Agregar");
        btnaddingadmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        btnaddingadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddingadminActionPerformed(evt);
            }
        });

        tbped_ing.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        tbped_ing.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbped_ing.setForeground(new java.awt.Color(0, 109, 86));
        tbped_ing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Ingrediente", "Cantidad_Cajas", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbped_ing.setGridColor(new java.awt.Color(0, 109, 86));
        tbped_ing.setRowHeight(25);
        tbped_ing.setSelectionBackground(new java.awt.Color(0, 109, 86));
        tbped_ing.setSelectionForeground(new java.awt.Color(110, 104, 104));
        tbped_ing.setShowGrid(false);
        tbped_ing.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tbped_ing);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 104, 104));
        jLabel4.setText("Total : ");

        txttotalpedido_ing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttotalpedido_ing.setForeground(new java.awt.Color(110, 104, 104));
        txttotalpedido_ing.setText(".......");

        btnpediringadmin.setBackground(new java.awt.Color(0, 109, 86));
        btnpediringadmin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnpediringadmin.setText("Pedir");
        btnpediringadmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));
        btnpediringadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpediringadminActionPerformed(evt);
            }
        });

        btncancelingadmin.setBackground(new java.awt.Color(0, 109, 86));
        btncancelingadmin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btncancelingadmin.setText("Cancelar");
        btncancelingadmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), null, null));

        tbstockactualpeding.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbstockactualpeding.setForeground(new java.awt.Color(0, 109, 86));
        tbstockactualpeding.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Ingrediente", "Stock_cajas", "Stock_total"
            }
        ));
        tbstockactualpeding.setGridColor(new java.awt.Color(0, 109, 86));
        tbstockactualpeding.setMinimumSize(new java.awt.Dimension(60, 100));
        tbstockactualpeding.setPreferredSize(new java.awt.Dimension(300, 100));
        jScrollPane2.setViewportView(tbstockactualpeding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGap(51, 51, 51)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbonomingre, 0, 405, Short.MAX_VALUE)
                        .addComponent(txtcantcajas))
                    .addGap(18, 18, 18)
                    .addComponent(btnaddingadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 31, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancelingadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(106, 106, 106)
                    .addComponent(btnpediringadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(174, 174, 174)
                    .addComponent(jLabel4)
                    .addGap(18, 18, 18)
                    .addComponent(txttotalpedido_ing)
                    .addGap(81, 81, 81)))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbonomingre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtcantcajas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddingadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btncancelingadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpediringadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotalpedido_ing))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddingadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddingadminActionPerformed
        // TODO add your handling code here:
        String nom_ing= (String)cbonomingre.getSelectedItem();//convierte a string el item seleccionado
        int cant_caj_ing= Integer.parseInt(txtcantcajas.getText());
        
        
    }//GEN-LAST:event_btnaddingadminActionPerformed

    private void btnpediringadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpediringadminActionPerformed
        // TODO add your handling code here:
        /*Tendra que agarrar todos los rows del jtable en un loop y meterlos con shift a una lista para q esa lista vaya al bd*/
    }//GEN-LAST:event_btnpediringadminActionPerformed

    private void cbonomingreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbonomingreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbonomingreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddingadmin;
    private javax.swing.JButton btncancelingadmin;
    private javax.swing.JButton btnpediringadmin;
    private javax.swing.JComboBox<String> cbonomingre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbped_ing;
    private javax.swing.JTable tbstockactualpeding;
    private javax.swing.JTextField txtcantcajas;
    private javax.swing.JLabel txttotalpedido_ing;
    // End of variables declaration//GEN-END:variables
}
