 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.utp.pizzatime.vista;

/**
 *
 * @author Dell
 */


public class RegistroIngresoo extends javax.swing.JPanel {

    /**
     * Creates new form RegistroIngresoo
     */
    public RegistroIngresoo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_Ingreso_Salida = new javax.swing.JTabbedPane();
        Panel_RegistroIngreso = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbprodingreso = new javax.swing.JTable();
        btncancelarprodingreso = new javax.swing.JButton();
        btnguardarprodingreso = new javax.swing.JButton();
        Text_FechaaIngreso = new javax.swing.JLabel();
        txtfechaingreso = new javax.swing.JTextField();
        Texto_RegistroIngreso = new javax.swing.JLabel();
        Text_Ingrediente = new javax.swing.JLabel();
        cboingingreso = new javax.swing.JComboBox<>();
        Text_CantidadCajas = new javax.swing.JLabel();
        txtcantcajasingreso = new javax.swing.JTextField();
        Text_Lote = new javax.swing.JLabel();
        txtloteingreso = new javax.swing.JTextField();
        Text_FechaCaducidad = new javax.swing.JLabel();
        txtfechacaducidad = new javax.swing.JTextField();
        Panel_RegistroSalida = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Productos_Salida = new javax.swing.JTable();
        Boton_Cancelar_Salida = new javax.swing.JButton();
        Boton_Guardar_Salida = new javax.swing.JButton();
        Text_Ingrediente1 = new javax.swing.JLabel();
        Texto_RegistroIngreso1 = new javax.swing.JLabel();
        ComboBox_Ingredientes_Salida = new javax.swing.JComboBox<>();
        Text_CantidadCajas1 = new javax.swing.JLabel();
        Field_CantidadCajas_Salida = new javax.swing.JTextField();
        Text_Lote1 = new javax.swing.JLabel();
        Field_Lote_Salida = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        Boton_Ingreso_Salida.setBackground(new java.awt.Color(0, 109, 86));

        Panel_RegistroIngreso.setBackground(new java.awt.Color(255, 255, 255));

        tbprodingreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Fecha de ingreso", "Fecha de caducidad"
            }
        ));
        jScrollPane2.setViewportView(tbprodingreso);

        btncancelarprodingreso.setBackground(new java.awt.Color(0, 109, 86));
        btncancelarprodingreso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncancelarprodingreso.setText("Cancelar");
        btncancelarprodingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarprodingresoActionPerformed(evt);
            }
        });

        btnguardarprodingreso.setBackground(new java.awt.Color(0, 109, 86));
        btnguardarprodingreso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardarprodingreso.setText("Guardar");
        btnguardarprodingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarprodingresoActionPerformed(evt);
            }
        });

        Text_FechaaIngreso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_FechaaIngreso.setText("Fecha de Ingreso");

        Texto_RegistroIngreso.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Texto_RegistroIngreso.setForeground(new java.awt.Color(0, 109, 86));
        Texto_RegistroIngreso.setText("Registro de Ingreso");

        Text_Ingrediente.setBackground(new java.awt.Color(0, 0, 0));
        Text_Ingrediente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_Ingrediente.setText("Ingrediente");

        cboingingreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboingingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboingingresoActionPerformed(evt);
            }
        });

        Text_CantidadCajas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_CantidadCajas.setText("Cantidad Cajas");

        txtcantcajasingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantcajasingresoActionPerformed(evt);
            }
        });

        Text_Lote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_Lote.setText("Lote");

        txtloteingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloteingresoActionPerformed(evt);
            }
        });

        Text_FechaCaducidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_FechaCaducidad.setText("Fecha Caducidad");

        txtfechacaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechacaducidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_RegistroIngresoLayout = new javax.swing.GroupLayout(Panel_RegistroIngreso);
        Panel_RegistroIngreso.setLayout(Panel_RegistroIngresoLayout);
        Panel_RegistroIngresoLayout.setHorizontalGroup(
            Panel_RegistroIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegistroIngresoLayout.createSequentialGroup()
                .addGroup(Panel_RegistroIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RegistroIngresoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(Panel_RegistroIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_RegistroIngresoLayout.createSequentialGroup()
                                .addComponent(Text_Ingrediente)
                                .addGap(35, 35, 35)
                                .addComponent(cboingingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Texto_RegistroIngreso)
                            .addGroup(Panel_RegistroIngresoLayout.createSequentialGroup()
                                .addGroup(Panel_RegistroIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_RegistroIngresoLayout.createSequentialGroup()
                                        .addComponent(Text_CantidadCajas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcantcajasingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(Text_Lote)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtloteingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistroIngresoLayout.createSequentialGroup()
                                        .addComponent(Text_FechaCaducidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfechacaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(Text_FechaaIngreso)))
                                .addGroup(Panel_RegistroIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_RegistroIngresoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_RegistroIngresoLayout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(btnguardarprodingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_RegistroIngresoLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btncancelarprodingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        Panel_RegistroIngresoLayout.setVerticalGroup(
            Panel_RegistroIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RegistroIngresoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Texto_RegistroIngreso)
                .addGap(15, 15, 15)
                .addGroup(Panel_RegistroIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Ingrediente)
                    .addComponent(cboingingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_RegistroIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcantcajasingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_Lote)
                    .addComponent(txtloteingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_CantidadCajas)
                    .addComponent(btnguardarprodingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_RegistroIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_FechaCaducidad)
                    .addComponent(txtfechacaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_FechaaIngreso)
                    .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btncancelarprodingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        Boton_Ingreso_Salida.addTab("Ingreso", Panel_RegistroIngreso);

        Panel_RegistroSalida.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Productos_Salida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Fecha de ingreso", "Fecha de caducidad"
            }
        ));
        jScrollPane3.setViewportView(Tabla_Productos_Salida);

        Boton_Cancelar_Salida.setBackground(new java.awt.Color(0, 109, 86));
        Boton_Cancelar_Salida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Boton_Cancelar_Salida.setText("Cancelar");
        Boton_Cancelar_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Cancelar_SalidaActionPerformed(evt);
            }
        });

        Boton_Guardar_Salida.setBackground(new java.awt.Color(0, 109, 86));
        Boton_Guardar_Salida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Boton_Guardar_Salida.setText("Guardar");
        Boton_Guardar_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Guardar_SalidaActionPerformed(evt);
            }
        });

        Text_Ingrediente1.setBackground(new java.awt.Color(0, 0, 0));
        Text_Ingrediente1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_Ingrediente1.setText("Ingrediente");

        Texto_RegistroIngreso1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Texto_RegistroIngreso1.setForeground(new java.awt.Color(0, 109, 86));
        Texto_RegistroIngreso1.setText("Registro de Salida");

        ComboBox_Ingredientes_Salida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Ingredientes_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_Ingredientes_SalidaActionPerformed(evt);
            }
        });

        Text_CantidadCajas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_CantidadCajas1.setText("Cantidad (Cajas o Unidades)");

        Text_Lote1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_Lote1.setText("Lote");

        Field_Lote_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_Lote_SalidaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Motivo");

        javax.swing.GroupLayout Panel_RegistroSalidaLayout = new javax.swing.GroupLayout(Panel_RegistroSalida);
        Panel_RegistroSalida.setLayout(Panel_RegistroSalidaLayout);
        Panel_RegistroSalidaLayout.setHorizontalGroup(
            Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegistroSalidaLayout.createSequentialGroup()
                .addGroup(Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RegistroSalidaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Texto_RegistroIngreso1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_RegistroSalidaLayout.createSequentialGroup()
                                .addComponent(Text_CantidadCajas1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Field_CantidadCajas_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Text_Lote1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Field_Lote_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel_RegistroSalidaLayout.createSequentialGroup()
                                .addGroup(Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text_Ingrediente1)
                                    .addComponent(jLabel1))
                                .addGap(35, 35, 35)
                                .addGroup(Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboBox_Ingredientes_Salida, 0, 245, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(Boton_Guardar_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Panel_RegistroSalidaLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(Boton_Cancelar_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        Panel_RegistroSalidaLayout.setVerticalGroup(
            Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RegistroSalidaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Texto_RegistroIngreso1)
                .addGroup(Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_RegistroSalidaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_Ingrediente1)
                            .addComponent(ComboBox_Ingredientes_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_RegistroSalidaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton_Guardar_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGroup(Panel_RegistroSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_CantidadCajas1)
                    .addComponent(Field_CantidadCajas_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_Lote1)
                    .addComponent(Field_Lote_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Boton_Cancelar_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        Boton_Ingreso_Salida.addTab("Salida", Panel_RegistroSalida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Boton_Ingreso_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(Boton_Ingreso_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarprodingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarprodingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarprodingresoActionPerformed

    private void btnguardarprodingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarprodingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarprodingresoActionPerformed

    private void cboingingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboingingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboingingresoActionPerformed

    private void txtloteingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloteingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloteingresoActionPerformed

    private void txtfechacaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechacaducidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechacaducidadActionPerformed

    private void Boton_Cancelar_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Cancelar_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Cancelar_SalidaActionPerformed

    private void Boton_Guardar_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Guardar_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Guardar_SalidaActionPerformed

    private void ComboBox_Ingredientes_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_Ingredientes_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_Ingredientes_SalidaActionPerformed

    private void Field_Lote_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_Lote_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_Lote_SalidaActionPerformed

    private void txtcantcajasingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantcajasingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantcajasingresoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Cancelar_Salida;
    private javax.swing.JButton Boton_Guardar_Salida;
    private javax.swing.JTabbedPane Boton_Ingreso_Salida;
    private javax.swing.JComboBox<String> ComboBox_Ingredientes_Salida;
    private javax.swing.JTextField Field_CantidadCajas_Salida;
    private javax.swing.JTextField Field_Lote_Salida;
    private javax.swing.JPanel Panel_RegistroIngreso;
    private javax.swing.JPanel Panel_RegistroSalida;
    private javax.swing.JTable Tabla_Productos_Salida;
    private javax.swing.JLabel Text_CantidadCajas;
    private javax.swing.JLabel Text_CantidadCajas1;
    private javax.swing.JLabel Text_FechaCaducidad;
    private javax.swing.JLabel Text_FechaaIngreso;
    private javax.swing.JLabel Text_Ingrediente;
    private javax.swing.JLabel Text_Ingrediente1;
    private javax.swing.JLabel Text_Lote;
    private javax.swing.JLabel Text_Lote1;
    private javax.swing.JLabel Texto_RegistroIngreso;
    private javax.swing.JLabel Texto_RegistroIngreso1;
    private javax.swing.JButton btncancelarprodingreso;
    private javax.swing.JButton btnguardarprodingreso;
    private javax.swing.JComboBox<String> cboingingreso;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbprodingreso;
    private javax.swing.JTextField txtcantcajasingreso;
    private javax.swing.JTextField txtfechacaducidad;
    private javax.swing.JTextField txtfechaingreso;
    private javax.swing.JTextField txtloteingreso;
    // End of variables declaration//GEN-END:variables
}
