/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.utp.pizzatime.view.multi;

import com.utp.pizzatime.util.SQLConexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BeeIsMega
 */
public class ConsultarStock extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarStock
     */
    public ConsultarStock() {
        initComponents();
        cargarDatosStock(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbconsultarstock = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        tbconsultarstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad Cajas", "Cantidad Unitaria"
            }
        ));
        jScrollPane1.setViewportView(tbconsultarstock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void cargarDatosStock() {
    try (Connection con = new SQLConexion().establecerConexion()) {
        String sql = "SELECT p.NOMBRE_PRO, SUM(d.CANTIDAD_CAJAS) AS CANTIDAD_CAJAS, "
                   + "SUM(d.CANTIDAD_CAJAS * p.STOCK_CAJAS) AS CANTIDAD_UNITARIA "
                   + "FROM DISPONIBLE d "
                   + "JOIN PRODUCTO p ON d.ID_PRO = p.ID_PRO "
                   + "GROUP BY p.NOMBRE_PRO";

        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tbconsultarstock.getModel();
        model.setRowCount(0); // Limpiar datos anteriores

        while (rs.next()) {
            Object[] fila = new Object[3];
            fila[0] = rs.getString("NOMBRE_PRO");
            fila[1] = rs.getInt("CANTIDAD_CAJAS");
            fila[2] = rs.getInt("CANTIDAD_UNITARIA");
            model.addRow(fila);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbconsultarstock;
    // End of variables declaration//GEN-END:variables
}
